apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-keyvault
spec:
  provider: azure
  secretObjects:
    {{- range $secret := .Values.secrets }}
    - secretName: {{ $secret.secretName }}
      type: Opaque
      data:
        {{- range $dataItem := $secret.data }}
        {{- if $dataItem.iterate }}
          {{- range $i := until (int $.Values.iterateCount) }}
          - objectName: "{{ $dataItem.vaultSecret }}-{{ $i }}"
            key: {{ $dataItem.key }}-{{ $i }}
          {{- end }}
        {{- else }}
          - objectName: "{{ $dataItem.vaultSecret }}"
            key: {{ $dataItem.key }}
        {{- end }}
        {{- end }}
    {{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.clientId }}
    keyvaultName: {{ .Values.azure.keyvaultName }}
    tenantId: {{ .Values.azure.tenantId }}
    objects: |
      array:
      {{- range $secret := .Values.secrets }}
        {{- range $dataItem := $secret.data }}
          {{- if $dataItem.iterate }}
            {{- range $i := until (int $.Values.iterateCount) }}
              - |
                objectName: "{{ $dataItem.vaultSecret }}-{{ $i }}"
                objectType: secret
            {{- end }}
          {{- else }}
              - |
                objectName: "{{ $dataItem.vaultSecret }}"
                objectType: secret
          {{- end }}
        {{- end }}
      {{- end }}