{{- $namespace := .Release.Namespace }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "elastic-search.fullname" . }}-values
  namespace: {{ $namespace }}
spec:
  endpoint: {{ .Values.azure.configEndpoint }}
  target:
    configMapName: configmap-values
    configMapData:
      type: yaml
      key: value.yaml
      separator: "."
  # auth:
  #   workloadIdentity:
  #     serviceAccountName: workload-identity-sa
  configuration:
     selectors:
        - keyFilter: "*"
          labelFilter: "elastic-values"
  secret:
    target:
      secretName: keystore
    configuration:
      selectors:
        - keyFilter: "*"
          labelFilter: "elastic-values"
      keyMapping:
        "elastic-storage-account": "azure.client.default.account" 
        "elastic-storage-container": "azure.client.default.container"