{{- if .Values.azure.storageAccountName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keystore
  namespace: {{ .Release.Namespace }}
stringData:
  azure.client.default.account: {{ .Values.azure.storageAccountName | quote }}
{{- end }}