---
apiVersion: v1
kind: Secret
metadata:
  name: keystore
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  azure.client.default.account: {{ .Values.azure.storageAccountName | b64enc | quote }}
