apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample.fullname" . }}-index-html
  namespace: {{ .Release.Namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Nginx on CBL-Mariner</title>
    </head>
    <body>
        <h1>Welcome to Nginx on CBL-Mariner!</h1>
        <p>This is a the dummy cluster-paas page.</p>
    </body>
    </html>