---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sample.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ include "sample.fullname" . }}-service
            port:
              number: 80
        path: {{ .Values.ingress.path | default "/" }}(/|$)(.*)
        pathType: Prefix
