apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sample.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "sample.selectorLabels" . | nindent 6 }}
