apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "sample.fullname" . }}-scaledobject
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "sample.fullname" . }}
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 100
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
