apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "sample.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80