apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-search
  namespace: default
spec:
  targetNamespace: elastic
  releaseName: elastic-search
  # Add dependsOn section here
  dependsOn:
    - name: elastic-operator
      namespace: flux-system
    - name: azure-keyvault-elastic
      namespace: default
  chart:
    spec:
      chart: ./charts/elastic-search
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: system-values
      valuesKey: values.yaml
  values:
    elasticsearch:
      instances:
        - version: 8.7.1
          storage:
            size: 30Gi
