---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-elastic
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: elastic
  releaseName: keyvault-secrets
  chart:
    spec:
      chart: ./charts/keyvault-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: system-values
      valuesKey: values.yaml
  values:
    identity: true
    secrets:
      - secretName: elasticsearch-credentials
        data:
          - key: username
            vaultSecret: elastic-username
            iterate: true
          - key: password
            vaultSecret: elastic-password
            iterate: true
          - key: key
            vaultSecret: elastic-key
            iterate: true
